---

  - name: Cloning repos personal-page
    git: 
      repo: https://github.com/BINSEM/personal-page.git
      dest: /home/pi/php-laravel
      version: php

  # - name: Move webroot to /var/www/binsemLravelPage
    